In [1]:
import pandas as pd

In [2]:
dfGC = pd.read_csv("Charges_Grocery_Supermarket.csv")

In [3]:
dfGC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1516 entries, 0 to 1515
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Record ID                  1482 non-null   object
 1   Related Record Type        1482 non-null   object
 2   Business Unique ID         1482 non-null   object
 3   Business Name              1482 non-null   object
 4   DBA/Trade Name             304 non-null    object
 5   Business Category          1482 non-null   object
 6   Certificate of Inspection  1481 non-null   object
 7   Inspection Number          1481 non-null   object
 8   NOH Number                 1482 non-null   object
 9   Violation Date             1482 non-null   object
 10  Charge                     1482 non-null   object
 11  Charge Count               1482 non-null   float64
 12  Cure Eligible              617 non-null    object
 13  Cured                      156 non-null    object
 14  Outcome                    1278 non-null   object
 15  Guilty                     1274 non-null   float64
 16  Not Guilty                 0 non-null      float64
 17  Dismissed                  0 non-null      float64
dtypes: float64(4), object(14)
memory usage: 213.3+ KB

In [4]:
dfALL = pd.read_csv("Charges_2.csv")

In [5]:
dfALL.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80712 entries, 0 to 80711
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Record ID                  80712 non-null  object
 1   Related Record Type        80712 non-null  object
 2   Business Unique ID         80712 non-null  object
 3   Business Name              80712 non-null  object
 4   DBA/Trade Name             7057 non-null   object
 5   Business Category          80708 non-null  object
 6   Certificate of Inspection  79688 non-null  object
 7   Inspection Number          79700 non-null  object
 8   NOH Number                 80712 non-null  object
 9   Violation Date             80712 non-null  object
 10  Charge                     80712 non-null  object
 11  Charge Count               80708 non-null  float64
 12  Cure Eligible              71630 non-null  object
 13  Cured                      8366 non-null   object
 14  Outcome                    63393 non-null  object
 15  Guilty                     58154 non-null  float64
 16  Not Guilty                 8836 non-null   float64
 17  Dismissed                  852 non-null    float64
dtypes: float64(4), object(14)
memory usage: 11.1+ MB

In [6]:
dfGC["Business Category"].value_counts()

Business Category
Grocery-Retail    1030
Supermarket        452
Name: count, dtype: int64

In [7]:
1030/1482

0.6950067476383266

In [76]:
unique_cats_violations = dfALL[["Business Category"]].value_counts()

In [78]:
unique_categories = dfALL["Business Category"].value_counts().index.tolist()

In [79]:
print(unique_categories)

['Tobacco Retail Dealer', 'Electronic Cigarette Dealer', 'Grocery-Retail', 'Supermarket', 'Misc Non-Food Retail', 'Garage & Parking Lot', 'Salons And Barbershop', 'Retail Laundry', 'Micromobility Device Store', 'Stoop Line Stand', 'Tax Preparers', 'Drug Store Retail', 'Car Wash', 'Home Improvement Contractor', 'Restaurant', 'Garage', 'Gas Station-Retail', 'Secondhand Dealer - General', 'Electronics Store', 'Secondhand Dealer - Auto', 'Wearing Apparel', 'Process Server Individual', 'Immigration Service Provider', 'Newsstand', 'Tow Truck Company', 'Electronic & Home Appliance Service Dealer', 'Parking Lot', 'Specialized Vending License - MFV', 'Hardware-Retail', 'Fuel Oil Dealer', 'Furniture Sales', 'Dry Cleaners', 'Pawnbroker', 'Employment Agency', 'Jewelry Store-Retail', 'Auto Rental', 'Dealer In Products For The Disabled', 'Debt Collection Agency', 'Sightseeing Bus', 'Megastore', 'Industrial Laundry', 'Retail Store', 'Movie Theater/Entertainment Venue', 'Funeral Homes', 'Booting Company', 'Third Party Food Delivery Service', 'Air Conditioning Law', 'Gaming Cafe', 'Gasoline Truck-Retail', 'Pedicab Business', 'Process Serving Agency', 'Horse Drawn Cab Owner', 'Other', 'Tow Truck Driver', 'Pedicab Driver', 'Scrap Metal Processor', 'General Vendor', 'Hotel/Motel', 'Amusement Arcade', 'Floor Coverings', 'Bingo Game Operator']

In [9]:
## how many business categories?
dfALL["Business Category"].nunique()

61

In [10]:
dfGC[["Business Category"]].value_counts()

Business Category
Grocery-Retail       1030
Supermarket           452
Name: count, dtype: int64

In [11]:
dfSupermarket = dfGC.query("`Business Category`=='Supermarket'")

In [54]:
dfGROCVios = dfGC.query("`Business Category`=='Grocery-Retail'")

In [ ]:
dfWHOLEVios = dfGC.query("`Business Category`=='Grocery-Retail'")

In [60]:
dfGROCVios = dfGROCVios.drop_duplicates(subset='Business Unique ID', keep='last')

In [61]:
dfGROCVios.sort_values('Charge Count', ascending = False)

,Record ID,Related Record Type,Business Unique ID,Business Name,DBA/Trade Name,Business Category,Certificate of Inspection,Inspection Number,NOH Number,Violation Date,Charge,Charge Count,Cure Eligible,Cured,Outcome,Guilty,Not Guilty,Dismissed
0,39669-2025-ADJC,dcwp_InspectionRequest,BA-1725618-2025,BARUIR COFFEE SHOP LLC,NaN,Grocery-Retail,A0218732,INS-000842402,25Q00843,03/28/2025,1 NYCRR § 221.5(c) - LABELS DO NOT CLEARLY STA...,2.0,No,No,Pleaded,2.0,NaN,NaN
813,22593-2024-ADJC,dcwp_InspectionRequest,BA-1693901-2024,NETOS GROUP MARKET LLC,NaN,Grocery-Retail,A0167876,INS-000741642,24M01198,05/07/2024,1 NYCRR § 221.5(c) - LABELS DO NOT CLEARLY STA...,2.0,NaN,NaN,Pleaded,2.0,NaN,NaN
865,28655-2024-ADJC,dcwp_InspectionRequest,BA-1310737-2022,Liberty Farms NY Inc,NaN,Grocery-Retail,A0185064,INS-000777252,24Q02059,08/27/2024,1 NYCRR § 221.5(c) - LABELS DO NOT CLEARLY STA...,2.0,No,NaN,Default Decision,2.0,NaN,NaN
861,21773-2024-ADJC,dcwp_InspectionRequest,BA-1419598-2022,NEW HARLEM HALAL MEAT INC,NaN,Grocery-Retail,A0164100,INS-000736148,24M01023,04/17/2024,1 NYCRR § 221.5(c) - LABELS DO NOT CLEARLY STA...,2.0,NaN,NaN,Pleaded,2.0,NaN,NaN
859,21669-2024-ADJC,dcwp_InspectionRequest,BA-1691165-2024,"MF Food, Vegetable & Gocery Inc",NaN,Grocery-Retail,A0164298,INS-000735344,24Q00779,04/18/2024,1 NYCRR § 221.5(c) - LABELS DO NOT CLEARLY STA...,2.0,No,NaN,Pleaded,2.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,15530-2023-ADJC,dcwp_InspectionRequest,BA-1655414-2023,Bani 03 Deli Grocery Corp.,NaN,Grocery-Retail,A0146972,INS-000696587,23X02045,12/14/2023,1 NYCRR § 221.13(b)(18) - DELI ITEMS DO NOT HA...,1.0,NaN,NaN,Default Decision,1.0,NaN,NaN
913,29901-2024-ADJC,dcwp_InspectionRequest,BA-1230140-2022,"RAANIA DELI & GROCERY, INC.",NaN,Grocery-Retail,A0188116,INS-000783007,24Q02310,09/13/2024,1 NYCRR § 221.5(c) - LABELS DO NOT CLEARLY STA...,1.0,No,NaN,Default Decision,1.0,NaN,NaN
912,19718-2024-ADJC,dcwp_InspectionRequest,BA-1200214-2022,CAZARES M. GROCERY CORP,NaN,Grocery-Retail,A0158911,INS-000725747,24N00606,03/18/2024,1 NYCRR § 221.13(b)(18) - DELI ITEMS DO NOT HA...,1.0,No,NaN,Pleaded,1.0,NaN,NaN
911,20180-2024-ADJC,dcwp_InspectionRequest,BA-1681689-2023,TRIADA MINIMARKET CORP,NaN,Grocery-Retail,A0159434,INS-000726644,24M00692,03/20/2024,1 NYCRR § 221.13(b)(18) - DELI ITEMS DO NOT HA...,1.0,NaN,NaN,Pleaded,1.0,NaN,NaN
995,17990-2024-ADJC,dcwp_InspectionRequest,BA-1520427-2022,"TRIBECA VILLAGE FARM, INC.",MORGAN'S MARKET,Grocery-Retail,A0154014,INS-000715854,24M00310,02/09/2024,NY Agri & Mkts § 190(5) - STORE DOES NOT HAVE ...,1.0,NaN,NaN,Pleaded,1.0,NaN,NaN

In [62]:
##top grocery store violators by charge count
dfGROCVios.head(5)

,Record ID,Related Record Type,Business Unique ID,Business Name,DBA/Trade Name,Business Category,Certificate of Inspection,Inspection Number,NOH Number,Violation Date,Charge,Charge Count,Cure Eligible,Cured,Outcome,Guilty,Not Guilty,Dismissed
0,39669-2025-ADJC,dcwp_InspectionRequest,BA-1725618-2025,BARUIR COFFEE SHOP LLC,NaN,Grocery-Retail,A0218732,INS-000842402,25Q00843,03/28/2025,1 NYCRR § 221.5(c) - LABELS DO NOT CLEARLY STA...,2.0,No,No,Pleaded,2.0,NaN,NaN
1,10016-2023-ADJC,dcwp_InspectionRequest,BA-1584016-2023,SUNSET PARK DELI CORP,NaN,Grocery-Retail,A0131953,INS-000660553,23N00949,08/18/2023,1 NYCRR § 221.5(c) - LABELS DO NOT CLEARLY STA...,1.0,NaN,NaN,Default Decision,1.0,NaN,NaN
2,39568-2025-ADJC,dcwp_InspectionRequest,BA-1239469-2022,DAVIEL DELI GROCERY CORP,NaN,Grocery-Retail,A0218582,INS-000842163,25X00542,03/28/2025,1 NYCRR § 221.13(b)(18) - DELI ITEMS DO NOT HA...,1.0,NaN,NaN,Pleaded,1.0,NaN,NaN
3,10024-2023-ADJC,dcwp_InspectionRequest,BA-1516146-2022,STANLEY MINI MARKET CORP,NaN,Grocery-Retail,A0131947,INS-000660547,23N00948,08/18/2023,1 NYCRR § 221.13(b)(18) - DELI ITEMS DO NOT HA...,1.0,NaN,NaN,Default Decision,1.0,NaN,NaN
4,10030-2023-ADJC,dcwp_InspectionRequest,BA-1175745-2022,"FARM IN THE MYRTLE DELI, INC.",NaN,Grocery-Retail,A0132126,INS-000660826,23N00967,08/21/2023,1 NYCRR § 221.13(b)(18) - DELI ITEMS DO NOT HA...,1.0,NaN,NaN,Default Decision,1.0,NaN,NaN

In [52]:
## find number of violations for supermarkets-- 359
dfSupermarketVios = dfSupermarket.drop_duplicates(subset='Business Unique ID', keep='last')

In [53]:
dfSupermarketVios.to_csv("SupermarketCharges.csv")

INSPECTIONS AND CONFISCATIONS

In [13]:
FoodInspections = pd.read_csv("FoodRetailerConf_ALL.csv")

In [14]:
FoodInspections.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8826 entries, 0 to 8825
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Certificate of Inspection      8826 non-null   object
 1   Inspection Number              8826 non-null   object
 2   Date of Occurance              8826 non-null   object
 3   Year (added)                   8826 non-null   object
 4   Business Unique ID             8820 non-null   object
 5   UniqueBusinessID_NoYear        8820 non-null   object
 6   Business Name                  8826 non-null   object
 7   DBA Trade Name                 2419 non-null   object
 8   Business Category              8826 non-null   object
 9   Inspection type                8826 non-null   object
 10  Device Category                8826 non-null   object
 11  Device Class                   8791 non-null   object
 12  Device Type                    8826 non-null   object
 13  Devices Inspected              8826 non-null   int64
 14  Devices Approved               8826 non-null   int64
 15  Devices Condemned/Confiscated  8826 non-null   int64
 16  Confiscated                    110 non-null    object
 17  Address Type                   8826 non-null   object
 18  Building Number                8799 non-null   object
 19  Street Name                    8826 non-null   object
 20  Street Name 2                  26 non-null     object
 21  Unit Type                      145 non-null    object
 22  Unit                           135 non-null    object
 23  City                           8826 non-null   object
 24  State                          8826 non-null   object
 25  Postcode                       8826 non-null   int64
 26  Borough                        8826 non-null   object
 27  Community Board                8813 non-null   float64
 28  Council District               8813 non-null   float64
 29  BIN                            8758 non-null   float64
 30  BBL                            8757 non-null   float64
 31  NTA                            8618 non-null   object
 32  Latitude                       8817 non-null   float64
 33  Longitude                      8817 non-null   float64
dtypes: float64(6), int64(4), object(24)
memory usage: 2.3+ MB

In [15]:
FoodInspections[["Business Category"]].value_counts()

Business Category
Grocery-Retail - 808           4792
Supermarket - 819              3985
Wholesale Food Market - 718      49
Name: count, dtype: int64

In [16]:
FoodInspections.sort_values(by='Date of Occurance', ascending=False)

,Certificate of Inspection,Inspection Number,Date of Occurance,Year (added),Business Unique ID,UniqueBusinessID_NoYear,Business Name,DBA Trade Name,Business Category,Inspection type,...,State,Postcode,Borough,Community Board,Council District,BIN,BBL,NTA,Latitude,Longitude
2686,A0205653,INS-000816733,12/31/2024,2024,BA-1442880-2022,BA-1442880,"NAMDOR, INC.",GRISTEDE'S STORE,Supermarket - 819,Scale,...,NY,10065,Manhattan,108.0,5.0,1045391.0,1.014600e+09,MN31,40.763563,-73.959082
6481,A0205689,INS-000816790,12/31/2024,2024,BA-1329047-2022,BA-1329047,I LOVE MY DELI GROCERY INC,NaN,Grocery-Retail - 808,Scale,...,NY,10304,Staten Island,501.0,49.0,5043692.0,5.029040e+09,SI08,40.609118,-74.089178
4999,A0205679,INS-000816770,12/31/2024,2024,BA-1461496-2022,BA-1461496,RADS DELI AND GRILL CORP,NaN,Grocery-Retail - 808,Scale,...,NY,11221,Brooklyn,304.0,37.0,3076283.0,3.033330e+09,BK78,40.693948,-73.917867
357,A0205670,INS-000816759,12/31/2024,2024,BA-1191323-2022,BA-1191323,DHY SONAMOO LLC,KEY FOOD,Supermarket - 819,Scale,...,NY,11212,Brooklyn,317.0,42.0,3103566.0,3.047160e+09,BK96,40.655333,-73.916004
3332,A0205670,INS-000816759,12/31/2024,2024,BA-1191323-2022,BA-1191323,DHY SONAMOO LLC,KEY FOOD,Supermarket - 819,Scale,...,NY,11212,Brooklyn,317.0,42.0,3103566.0,3.047160e+09,BK96,40.655333,-73.916004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2592,A0148788,INS-000699873,01/02/2024,2024,BA-1466635-2022,BA-1466635,P & M UTOPIA LLC,NaN,Supermarket - 819,Scale,...,NY,11358,Queens,411.0,19.0,4124761.0,4.055280e+09,QN48,40.752988,-73.792056
3744,A0148800,INS-000699896,01/02/2024,2024,BA-1682124-2024,BA-1682124,7918 MEAT & PRODUCE CORP,C-TOWN SUPERMARKET,Supermarket - 819,Scale,...,NY,11209,Brooklyn,310.0,47.0,3150828.0,3.059780e+09,BK31,40.628365,-74.029069
7544,A0148734,INS-000699795,01/02/2024,2024,BA-1186419-2022,BA-1186419,CARNICERIA-DELI PLAUTILA CORP,NaN,Grocery-Retail - 808,Scale,...,NY,11218,Brooklyn,312.0,39.0,3124493.0,3.053320e+09,BK41,40.642453,-73.980279
5724,A0148802,INS-000699901,01/02/2024,2024,BA-1414062-2022,BA-1414062,MARIA'S BEAUTIFUL ARRANGEMENTS INC,NaN,Grocery-Retail - 808,Scale,...,NY,11223,Brooklyn,313.0,47.0,3187036.0,3.069040e+09,BK26,40.588815,-73.983769
3743,A0148800,INS-000699896,01/02/2024,2024,BA-1682124-2024,BA-1682124,7918 MEAT & PRODUCE CORP,C-TOWN SUPERMARKET,Supermarket - 819,Scale,...,NY,11209,Brooklyn,310.0,47.0,3150828.0,3.059780e+09,BK31,40.628365,-74.029069

In [17]:
FoodInspections.drop_duplicates(subset='UniqueBusinessID_NoYear', keep='last')

,Certificate of Inspection,Inspection Number,Date of Occurance,Year (added),Business Unique ID,UniqueBusinessID_NoYear,Business Name,DBA Trade Name,Business Category,Inspection type,...,State,Postcode,Borough,Community Board,Council District,BIN,BBL,NTA,Latitude,Longitude
14,A0200942,INS-000804414,11/26/2024,2024,BA-1714440-2024,BA-1714440,WING Y MEATS INC,NaN,Wholesale Food Market - 718,Scale,...,NY,11222,Brooklyn,301.0,33.0,3066690.0,3.026640e+09,BK76,40.726249,-73.935830
77,A0191624,INS-000789240,10/02/2024,2024,BA-1710607-2024,BA-1710607,WILLOW WISP ORGANIC FARM,NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
91,A0185672,INS-000778385,08/29/2024,2024,BA-1707588-2024,BA-1707588,"WFM PRIVATE LABEL MANAGEMENT, INC.",NaN,Wholesale Food Market - 718,Scale,...,NY,11101,Queens,402.0,26.0,4005259.0,4.004540e+09,QN31,40.751142,-73.949752
116,A0196906,INS-000793824,10/31/2024,2024,BA-1711597-2024,BA-1711597,W.E.A.M. CORPORATION,NaN,Wholesale Food Market - 718,Scale,...,NY,10465,Bronx,210.0,13.0,2080400.0,2.055620e+09,BX52,40.824635,-73.820366
118,A0149537,INS-000699233,01/09/2024,2024,BA-1477512-2022,BA-1477512,victor provision inc.,NaN,Wholesale Food Market - 718,Scale,...,NY,11206,Brooklyn,301.0,34.0,3070908.0,3.030390e+09,BK78,40.710334,-73.934940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8818,A0211380,INS-000828831,02/11/2025,2025,BA-1126757-2022,BA-1126757,10014 Corp.,NaN,Grocery-Retail - 808,Scale,...,NY,11375,Queens,406.0,29.0,4075137.0,4.031700e+09,QN17,40.726862,-73.853472
8821,A0153288,INS-000712001,02/05/2024,2024,BA-1100777-2022,BA-1100777,10014 CORP,NaN,Grocery-Retail - 808,Scale,...,NY,11375,Queens,406.0,29.0,4075137.0,4.031700e+09,QN17,40.726862,-73.853472
8823,A0211276,INS-000828679,02/11/2025,2025,BA-1685010-2024,BA-1685010,100 MARKET PLACE INC.,NaN,Grocery-Retail - 808,Scale,...,NY,10004,Manhattan,101.0,1.0,1000022.0,1.000100e+09,MN25,40.703512,-74.011606
8824,A0181228,INS-000769245,08/02/2024,2024,BA-1584111-2023,BA-1584111,1 OCEAN DELI CORP.,NaN,Grocery-Retail - 808,Scale,...,NY,10035,Manhattan,111.0,9.0,1054407.0,1.017700e+09,MN34,40.802074,-73.939113
8825,A0179388,INS-000764707,07/23/2024,2024,BA-1625844-2023,BA-1625844,1 GUADALUPE VICTORIA INC.,NaN,Grocery-Retail - 808,Scale,...,NY,10033,Manhattan,112.0,10.0,1063762.0,1.021570e+09,MN35,40.851321,-73.932258

In [18]:
FoodInspections.drop_duplicates(subset='Business Unique ID', keep='last')

,Certificate of Inspection,Inspection Number,Date of Occurance,Year (added),Business Unique ID,UniqueBusinessID_NoYear,Business Name,DBA Trade Name,Business Category,Inspection type,...,State,Postcode,Borough,Community Board,Council District,BIN,BBL,NTA,Latitude,Longitude
14,A0200942,INS-000804414,11/26/2024,2024,BA-1714440-2024,BA-1714440,WING Y MEATS INC,NaN,Wholesale Food Market - 718,Scale,...,NY,11222,Brooklyn,301.0,33.0,3066690.0,3.026640e+09,BK76,40.726249,-73.935830
77,A0191624,INS-000789240,10/02/2024,2024,BA-1710607-2024,BA-1710607,WILLOW WISP ORGANIC FARM,NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
91,A0185672,INS-000778385,08/29/2024,2024,BA-1707588-2024,BA-1707588,"WFM PRIVATE LABEL MANAGEMENT, INC.",NaN,Wholesale Food Market - 718,Scale,...,NY,11101,Queens,402.0,26.0,4005259.0,4.004540e+09,QN31,40.751142,-73.949752
116,A0196906,INS-000793824,10/31/2024,2024,BA-1711597-2024,BA-1711597,W.E.A.M. CORPORATION,NaN,Wholesale Food Market - 718,Scale,...,NY,10465,Bronx,210.0,13.0,2080400.0,2.055620e+09,BX52,40.824635,-73.820366
118,A0149537,INS-000699233,01/09/2024,2024,BA-1477512-2022,BA-1477512,victor provision inc.,NaN,Wholesale Food Market - 718,Scale,...,NY,11206,Brooklyn,301.0,34.0,3070908.0,3.030390e+09,BK78,40.710334,-73.934940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8818,A0211380,INS-000828831,02/11/2025,2025,BA-1126757-2022,BA-1126757,10014 Corp.,NaN,Grocery-Retail - 808,Scale,...,NY,11375,Queens,406.0,29.0,4075137.0,4.031700e+09,QN17,40.726862,-73.853472
8821,A0153288,INS-000712001,02/05/2024,2024,BA-1100777-2022,BA-1100777,10014 CORP,NaN,Grocery-Retail - 808,Scale,...,NY,11375,Queens,406.0,29.0,4075137.0,4.031700e+09,QN17,40.726862,-73.853472
8823,A0211276,INS-000828679,02/11/2025,2025,BA-1685010-2024,BA-1685010,100 MARKET PLACE INC.,NaN,Grocery-Retail - 808,Scale,...,NY,10004,Manhattan,101.0,1.0,1000022.0,1.000100e+09,MN25,40.703512,-74.011606
8824,A0181228,INS-000769245,08/02/2024,2024,BA-1584111-2023,BA-1584111,1 OCEAN DELI CORP.,NaN,Grocery-Retail - 808,Scale,...,NY,10035,Manhattan,111.0,9.0,1054407.0,1.017700e+09,MN34,40.802074,-73.939113
8825,A0179388,INS-000764707,07/23/2024,2024,BA-1625844-2023,BA-1625844,1 GUADALUPE VICTORIA INC.,NaN,Grocery-Retail - 808,Scale,...,NY,10033,Manhattan,112.0,10.0,1063762.0,1.021570e+09,MN35,40.851321,-73.932258

In [19]:
SUPEInspections = FoodInspections.query("`Business Category`=='Supermarket - 819'")

In [20]:
GROCInspections = FoodInspections.query("`Business Category`=='Grocery-Retail - 808'")

In [21]:
WHOLEInspections = FoodInspections.query("`Business Category`=='Wholesale Food Market - 718'")

In [22]:
SUPEInspections.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3985 entries, 0 to 4033
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Certificate of Inspection      3985 non-null   object
 1   Inspection Number              3985 non-null   object
 2   Date of Occurance              3985 non-null   object
 3   Year (added)                   3985 non-null   object
 4   Business Unique ID             3983 non-null   object
 5   UniqueBusinessID_NoYear        3983 non-null   object
 6   Business Name                  3985 non-null   object
 7   DBA Trade Name                 1653 non-null   object
 8   Business Category              3985 non-null   object
 9   Inspection type                3985 non-null   object
 10  Device Category                3985 non-null   object
 11  Device Class                   3973 non-null   object
 12  Device Type                    3985 non-null   object
 13  Devices Inspected              3985 non-null   int64
 14  Devices Approved               3985 non-null   int64
 15  Devices Condemned/Confiscated  3985 non-null   int64
 16  Confiscated                    67 non-null     object
 17  Address Type                   3985 non-null   object
 18  Building Number                3983 non-null   object
 19  Street Name                    3985 non-null   object
 20  Street Name 2                  0 non-null      object
 21  Unit Type                      28 non-null     object
 22  Unit                           24 non-null     object
 23  City                           3985 non-null   object
 24  State                          3985 non-null   object
 25  Postcode                       3985 non-null   int64
 26  Borough                        3985 non-null   object
 27  Community Board                3979 non-null   float64
 28  Council District               3979 non-null   float64
 29  BIN                            3961 non-null   float64
 30  BBL                            3961 non-null   float64
 31  NTA                            3932 non-null   object
 32  Latitude                       3981 non-null   float64
 33  Longitude                      3981 non-null   float64
dtypes: float64(6), int64(4), object(24)
memory usage: 1.1+ MB

In [28]:
SUPEConfInspections = SUPEInspections.query("`Devices Condemned/Confiscated` > 0")

In [46]:
GROCConfInspections = GROCInspections.query("`Devices Condemned/Confiscated` > 0")

In [47]:
GROCConfInspections.sort_values('Devices Condemned/Confiscated', ascending = False)

,Certificate of Inspection,Inspection Number,Date of Occurance,Year (added),Business Unique ID,UniqueBusinessID_NoYear,Business Name,DBA Trade Name,Business Category,Inspection type,...,State,Postcode,Borough,Community Board,Council District,BIN,BBL,NTA,Latitude,Longitude
6305,A0190399,INS-000787054,09/26/2024,2024,BA-1690979-2024,BA-1690979,JOE BAKERY INC.,NaN,Grocery-Retail - 808,Scale,...,NY,11214,Brooklyn,311.0,38.0,3165753.0,3.063440e+09,BK28,40.607665,-74.002125
7300,A0162386,INS-000731913,04/05/2024,2024,BA-1690494-2024,BA-1690494,DELI COMBO INC,NaN,Grocery-Retail - 808,Scale,...,NY,10305,Staten Island,502.0,50.0,5050128.0,5.033910e+09,SI14,40.593794,-74.080454
6503,A0188361,INS-000785368,09/17/2024,2024,BA-1679440-2023,BA-1679440,HONOR GROCERY & DELI CORP.,NaN,Grocery-Retail - 808,Scale,...,NY,10456,Bronx,204.0,16.0,2002688.0,2.024530e+09,BX14,40.834021,-73.915761
8199,A0187256,INS-000781391,09/10/2024,2024,BA-1121078-2022,BA-1121078,AF RIVERDALE MEAT MARKET CORP,NaN,Grocery-Retail - 808,Scale,...,NY,10463,Bronx,208.0,11.0,2083160.0,2.057040e+09,BX29,40.879138,-73.904649
4100,A0202625,INS-000810921,12/06/2024,2024,BA-1716203-2024,BA-1716203,YDHNY INC,NaN,Grocery-Retail - 808,Scale,...,NY,11210,Brooklyn,317.0,45.0,3114503.0,3.050160e+09,BK91,40.636004,-73.937402
4753,A0177190,INS-000760345,07/09/2024,2024,BA-1534786-2022,BA-1534786,SAYYAF FOOD CORP,NaN,Grocery-Retail - 808,Scale,...,NY,11212,Brooklyn,316.0,42.0,3082837.0,3.036250e+09,BK81,40.657690,-73.907683
6304,A0166954,INS-000739789,05/02/2024,2024,BA-1690979-2024,BA-1690979,JOE BAKERY INC.,NaN,Grocery-Retail - 808,Scale,...,NY,11214,Brooklyn,311.0,38.0,3165753.0,3.063440e+09,BK28,40.607665,-74.002125
5662,A0171842,INS-000749613,05/31/2024,2024,BA-1429125-2022,BA-1429125,MERRICK MEAT MARKET INC,NaN,Grocery-Retail - 808,Scale,...,NY,11433,Queens,412.0,27.0,4216668.0,4.101780e+09,QN01,40.697712,-73.786188
6218,A0154772,INS-000717591,02/16/2024,2024,BA-1282904-2022,BA-1282904,KAMLIN III LLC,NaN,Grocery-Retail - 808,Scale,...,NY,11209,Brooklyn,310.0,47.0,3145708.0,3.058720e+09,BK31,40.634295,-74.023664
7400,A0178415,INS-000762832,07/17/2024,2024,BA-1209860-2022,BA-1209860,CONCORD MARKET CORP.,CONCORD MARKET,Grocery-Retail - 808,Scale,...,NY,11201,Brooklyn,302.0,33.0,3325911.0,3.000860e+09,BK38,40.696153,-73.987414
5826,A0190608,INS-000778173,09/26/2024,2024,BA-1707531-2024,BA-1707531,"LUS LICENSING, LLC",Lidl-1576,Grocery-Retail - 808,Scale,...,NY,11004,Queens,413.0,23.0,4439455.0,4.085130e+09,QN44,40.746568,-73.712837
6126,A0180040,INS-000766726,07/26/2024,2024,BA-1329374-2022,BA-1329374,KKISB CORP,LAST STOP DELI,Grocery-Retail - 808,Scale,...,NY,11209,Brooklyn,310.0,47.0,3156122.0,3.061370e+09,BK31,40.612699,-74.033777
7561,A0197617,INS-000801526,11/06/2024,2024,BA-1202042-2022,BA-1202042,CARNICERA LA PALMA & MINI MARKET CORP,NaN,Grocery-Retail - 808,Scale,...,NY,11421,Queens,409.0,32.0,4183704.0,4.089190e+09,QN53,40.692252,-73.861330
6476,A0148906,INS-000700172,01/03/2024,2024,BA-1582436-2023,BA-1582436,IBERIE DELI GROCERY CORP,PAMELA GREEN DELI,Grocery-Retail - 808,Scale,...,NY,10456,Bronx,203.0,17.0,2004858.0,2.026690e+09,BX35,40.822662,-73.902880
6376,A0130058,INS-000657033,08/03/2023,2023,BA-1572278-2023,BA-1572278,Jamaica Finest Meat Corp,Green Valley Supermarket,Grocery-Retail - 808,Scale,...,NY,11421,Queens,409.0,32.0,4183846.0,4.089220e+09,QN53,40.692521,-73.858906
7008,A0153917,INS-000715650,02/02/2024,2024,BA-1208677-2022,BA-1208677,EXPRESS DELI GROCERY INC I,NaN,Grocery-Retail - 808,Scale,...,NY,11215,Brooklyn,306.0,39.0,3337650.0,3.010170e+09,BK37,40.667788,-73.986897
7297,A0138886,INS-000681923,10/11/2023,2023,BA-1227987-2022,BA-1227987,DELI FOR ME CORP,NaN,Grocery-Retail - 808,Scale,...,NY,11432,Queens,412.0,23.0,4212903.0,4.099360e+09,QN61,40.714959,-73.774182
5820,A0194389,INS-000794929,10/17/2024,2024,BA-1451804-2022,BA-1451804,M & A FRUITS & DELI CORP,NaN,Grocery-Retail - 808,Scale,...,NY,10457,Bronx,206.0,15.0,2011976.0,2.030680e+09,BX17,40.846801,-73.893125
7698,A0146217,INS-000695261,12/08/2023,2023,BA-1002976-2022,BA-1002976,BRAUN TUNA,NaN,Grocery-Retail - 808,Scale,...,NY,11367,Queens,408.0,24.0,4143394.0,4.066210e+09,QN37,40.726263,-73.821627
7798,A0158731,INS-000725329,03/15/2024,2024,BA-1107968-2022,BA-1107968,BEST EMMONS BAGEL INC.,NaN,Grocery-Retail - 808,Scale,...,NY,11235,Brooklyn,315.0,48.0,3342943.0,3.087830e+09,BK17,40.583692,-73.944719
7963,A0151842,INS-000708701,01/26/2024,2024,BA-1631875-2023,BA-1631875,ASIAN FOOD 888 INC,NaN,Grocery-Retail - 808,Scale,...,NY,11355,Outside NYC,407.0,20.0,4114281.0,4.050430e+09,QN22,40.757317,-73.829041
4614,A0149465,INS-000701292,01/09/2024,2024,BA-1520854-2022,BA-1520854,SOUTH ROAD GUY_R INC.,NaN,Grocery-Retail - 808,Scale,...,NY,11433,Queens,412.0,28.0,4215802.0,4.101290e+09,QN01,40.699497,-73.794199
4279,A0142377,INS-000687867,11/09/2023,2023,BA-1666365-2023,BA-1666365,Urban Deli & Convenience Corp.,NaN,Grocery-Retail - 808,Scale,...,NY,11366,Queens,408.0,24.0,4155489.0,4.072290e+09,QN06,40.726652,-73.788927
6534,A0182094,INS-000770954,08/08/2024,2024,BA-1321896-2022,BA-1321896,HIGHLINE DELI II CORP.,NaN,Grocery-Retail - 808,Scale,...,NY,10002,Manhattan,103.0,1.0,1079647.0,1.003000e+09,MN27,40.715290,-73.993150
7369,A0211937,INS-000829848,02/13/2025,2025,BA-1596353-2023,BA-1596353,CROSBY DELI & GROCERY INC.,NaN,Grocery-Retail - 808,Scale,...,NY,10461,Bronx,210.0,13.0,2074737.0,2.053970e+09,BX52,40.841406,-73.829847
8220,A0209963,INS-000826278,01/31/2025,2025,BA-1677877-2023,BA-1677877,ACEMAK DELI & GROCERY INC,NaN,Grocery-Retail - 808,Scale,...,NY,10457,Bronx,205.0,15.0,2013318.0,2.031430e+09,BX41,40.852148,-73.898973
8432,A0211329,INS-000828757,02/11/2025,2025,BA-1001621-2022,BA-1001621,"53RD ST. FOOD, LLC.",BLAKE & TODD,Grocery-Retail - 808,Scale,...,NY,10022,Manhattan,105.0,4.0,1083869.0,1.012880e+09,MN17,40.759445,-73.973552
7592,A0207621,INS-000820442,01/15/2025,2025,BA-1219880-2022,BA-1219880,"CAFE BRAVO, INC.",NaN,Grocery-Retail - 808,Scale,...,NY,10001,Manhattan,104.0,3.0,1013511.0,1.007540e+09,MN13,40.751084,-73.997972
4079,A0207803,INS-000820719,01/16/2025,2025,BA-1708856-2024,BA-1708856,YUM DELI AND GROCERY 1 CORP.,NaN,Grocery-Retail - 808,Scale,...,NY,11224,Brooklyn,313.0,47.0,3189522.0,3.070510e+09,BK21,40.572869,-73.995069
6635,A0204696,INS-000814847,12/20/2024,2024,BA-1642873-2023,BA-1642873,GUIDY DELI AND GROCERY INC,NaN,Grocery-Retail - 808,Scale,...,NY,10466,Bronx,212.0,12.0,2064690.0,2.048660e+09,BX44,40.889324,-73.852163
6444,A0214445,INS-000833934,03/04/2025,2025,BA-1722946-2025,BA-1722946,ISAAC FISH MARKET INC.,NaN,Grocery-Retail - 808,Scale,...,NY,10453,Bronx,205.0,14.0,2008632.0,2.028700e+09,NaN,40.853800,-73.908719
6209,A0189230,INS-000784954,09/20/2024,2024,BA-1335574-2022,BA-1335574,KARMA FARMERS MARKET INC,FAMILY FRUIT,Grocery-Retail - 808,Scale,...,NY,10306,Staten Island,502.0,50.0,5053640.0,5.037000e+09,SI45,40.575357,-74.104824
6091,A0207738,INS-000820625,01/15/2025,2025,BA-1168744-2022,BA-1168744,L.P. MINI MARKET CORP,NaN,Grocery-Retail - 808,Scale,...,NY,11412,Queens,412.0,27.0,4222057.0,4.104400e+09,NaN,40.700760,-73.764330
5827,A0208809,INS-000822721,01/24/2025,2025,BA-1628903-2023,BA-1628903,LUPITAS MEXICAN GROCERY II INC,LUPITAS MEXICAN GROCERY II,Grocery-Retail - 808,Scale,...,NY,10466,Bronx,212.0,11.0,2093687.0,2.048350e+09,BX44,40.893899,-73.858989
5751,A0213881,INS-000832954,02/28/2025,2025,BA-1596402-2023,BA-1596402,MANHATTAN BEST DELI & GRILL INC,NaN,Grocery-Retail - 808,Scale,...,NY,10032,Manhattan,112.0,10.0,1062995.0,1.021250e+09,MN36,40.840571,-73.938290
5091,A0207014,INS-000819327,01/10/2025,2025,BA-1412248-2022,BA-1412248,"PREMIER FOOD, INC.",NaN,Grocery-Retail - 808,Scale,...,NY,10462,Bronx,211.0,13.0,2048796.0,2.042880e+09,BX49,40.854461,-73.866168
4685,A0213715,INS-000832702,02/27/2025,2025,BA-1721260-2025,BA-1721260,SILVER MOON DELI INC.,NaN,Grocery-Retail - 808,Scale,...,NY,10032,Manhattan,112.0,10.0,1062822.0,1.021190e+09,MN36,40.836067,-73.943400
4440,A0192868,INS-000791742,10/08/2024,2024,BA-1484729-2022,BA-1484729,"TERRY-RAM, LTD.",NaN,Grocery-Retail - 808,Scale,...,NY,10282,Manhattan,101.0,1.0,1085486.0,1.000160e+09,MN25,40.717930,-74.014523
4387,A0213473,INS-000832340,02/26/2025,2025,BA-1720823-2025,BA-1720823,TINGO FOOD MARKET CORPORATION,NaN,Grocery-Retail - 808,Scale,...,NY,10453,Bronx,205.0,14.0,2007948.0,2.028290e+09,BX41,40.853268,-73.905933
4231,A0204578,INS-000814634,12/19/2024,2024,BA-1597771-2023,BA-1597771,VICTOR’S BAKERY CORP,NaN,Grocery-Retail - 808,Scale,...,NY,10453,Bronx,205.0,14.0,2007693.0,2.028080e+09,BX41,40.851985,-73.903976
8727,A0208287,INS-000835596,01/22/2025,2025,BA-1616765-2023,BA-1616765,1407 WESTSIDE MARKET LLC,WESTSIDE MARKET,Grocery-Retail - 808,Scale,...,NY,10128,Manhattan,108.0,5.0,1048344.0,1.015210e+09,MN40,40.783449,-73.952685

In [34]:
SUPEConfInspections["Business Unique ID"].value_counts()

Business Unique ID
BA-1641965-2023    3
BA-1402553-2022    3
BA-1460189-2022    2
BA-1200637-2022    2
BA-1547869-2022    2
BA-1119903-2022    2
BA-1504165-2022    2
BA-1722159-2025    2
BA-1102781-2022    1
BA-1682507-2024    1
BA-1105393-2022    1
BA-966535-2022     1
BA-1559348-2022    1
BA-1125576-2022    1
BA-1084519-2022    1
BA-1682124-2024    1
BA-991760-2022     1
BA-1709418-2024    1
BA-1635802-2023    1
BA-1106514-2022    1
BA-1200670-2022    1
BA-1122304-2022    1
BA-1722356-2025    1
BA-1126212-2022    1
BA-1108214-2022    1
BA-1102863-2022    1
BA-1095829-2022    1
BA-1600499-2023    1
BA-1664090-2023    1
BA-1126555-2022    1
BA-1248176-2022    1
BA-1184052-2022    1
BA-1204280-2022    1
BA-1468736-2022    1
BA-1515506-2022    1
BA-1681549-2023    1
BA-1617911-2023    1
BA-1265605-2022    1
BA-1692104-2024    1
BA-1451784-2022    1
BA-1427902-2022    1
BA-1445937-2022    1
BA-1453747-2022    1
BA-1392192-2022    1
BA-1429125-2022    1
BA-1219411-2022    1
BA-1708496-2024    1
BA-1322704-2022    1
BA-1284348-2022    1
BA-1708904-2024    1
BA-1283392-2022    1
BA-1726866-2025    1
BA-1314764-2022    1
BA-1689185-2024    1
BA-1194361-2022    1
BA-1201519-2022    1
BA-1112199-2022    1
Name: count, dtype: int64

In [42]:
SUPEConfInspections.value_counts('Devices Condemned/Confiscated')

Devices Condemned/Confiscated
1    22
3    17
4    13
2    12
6     3
Name: count, dtype: int64

In [45]:
SUPEConfInspections.sort_values('Devices Condemned/Confiscated', ascending = False)

,Certificate of Inspection,Inspection Number,Date of Occurance,Year (added),Business Unique ID,UniqueBusinessID_NoYear,Business Name,DBA Trade Name,Business Category,Inspection type,...,State,Postcode,Borough,Community Board,Council District,BIN,BBL,NTA,Latitude,Longitude
2616,A0157584,INS-000710522,03/08/2024,2024,BA-1453747-2022,BA-1453747,NSR FOOD DISTRIBUTORS INC,SCOTTY’S MARKETPLACE,Supermarket - 819,Scale,...,NY,10307,Staten Island,503.0,51.0,5141719.0,5.080080e+09,SI11,40.518013,-74.234458
3775,A0159416,INS-000726616,03/20/2024,2024,BA-1635802-2023,BA-1635802,597 FOOD CORP.,NaN,Supermarket - 819,Scale,...,NY,11226,Brooklyn,314.0,45.0,3121219.0,3.052370e+09,BK42,40.635559,-73.962399
3892,A0162293,INS-000731768,04/05/2024,2024,BA-1102863-2022,BA-1102863,2358 Meat Corp,NaN,Supermarket - 819,Scale,...,NY,10468,Bronx,207.0,14.0,2014612.0,2.032120e+09,BX30,40.861680,-73.905889
2509,A0177017,INS-000759988,07/09/2024,2024,BA-1451784-2022,BA-1451784,R.J. CASTLE HILL FOOD CORP,NaN,Supermarket - 819,Scale,...,NY,10462,Bronx,209.0,18.0,2029044.0,2.039350e+09,BX46,40.835253,-73.851987
3114,A0155485,INS-000731779,02/23/2024,2024,BA-1314764-2022,BA-1314764,GOLDEN BOYS GROUP INC,NaN,Supermarket - 819,Scale,...,NY,11208,Brooklyn,305.0,37.0,3093424.0,3.041660e+09,BK83,40.678545,-73.870797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2598,A0203747,INS-000812984,12/13/2024,2024,BA-1445937-2022,BA-1445937,ORCHARD SUPERMARKET CORP,ORCHARD FINE FOODS,Supermarket - 819,Scale,...,NY,11375,Queens,406.0,29.0,4078798.0,4.032920e+09,QN17,40.719435,-73.839459
2497,A0217374,INS-000839092,03/20/2025,2025,BA-1692104-2024,BA-1692104,"RALPH AVENUE MEAT, CORP.",NaN,Supermarket - 819,Scale,...,NY,11236,Brooklyn,318.0,46.0,3223371.0,3.079790e+09,BK58,40.632841,-73.918691
2346,A0208801,INS-000822706,01/24/2025,2025,BA-1681549-2023,BA-1681549,SWF FOOD CORP.,Met Food,Supermarket - 819,Scale,...,NY,11372,Queens,403.0,25.0,4029863.0,4.012870e+09,QN28,40.749176,-73.889698
2321,A0146939,INS-000738275,12/14/2023,2023,BA-1547869-2022,BA-1547869,TEJADA MEAT CORP.,NaN,Supermarket - 819,Scale,...,NY,10455,Bronx,201.0,8.0,2004428.0,2.026230e+09,BX34,40.815761,-73.908186
4016,A0212301,INS-000830463,02/18/2025,2025,BA-1112199-2022,BA-1112199,116-15 GMV CORP.,NaN,Supermarket - 819,Scale,...,NY,11418,Queens,409.0,29.0,4079441.0,4.033240e+09,QN60,40.707295,-73.835452

In [44]:
SUPEConfInspections.to_csv("Supermarkets With Confiscations.csv")

In [23]:
GROCInspections.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4792 entries, 4034 to 8825
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Certificate of Inspection      4792 non-null   object
 1   Inspection Number              4792 non-null   object
 2   Date of Occurance              4792 non-null   object
 3   Year (added)                   4792 non-null   object
 4   Business Unique ID             4788 non-null   object
 5   UniqueBusinessID_NoYear        4788 non-null   object
 6   Business Name                  4792 non-null   object
 7   DBA Trade Name                 759 non-null    object
 8   Business Category              4792 non-null   object
 9   Inspection type                4792 non-null   object
 10  Device Category                4792 non-null   object
 11  Device Class                   4770 non-null   object
 12  Device Type                    4792 non-null   object
 13  Devices Inspected              4792 non-null   int64
 14  Devices Approved               4792 non-null   int64
 15  Devices Condemned/Confiscated  4792 non-null   int64
 16  Confiscated                    41 non-null     object
 17  Address Type                   4792 non-null   object
 18  Building Number                4790 non-null   object
 19  Street Name                    4792 non-null   object
 20  Street Name 2                  2 non-null      object
 21  Unit Type                      117 non-null    object
 22  Unit                           111 non-null    object
 23  City                           4792 non-null   object
 24  State                          4792 non-null   object
 25  Postcode                       4792 non-null   int64
 26  Borough                        4792 non-null   object
 27  Community Board                4786 non-null   float64
 28  Council District               4786 non-null   float64
 29  BIN                            4773 non-null   float64
 30  BBL                            4772 non-null   float64
 31  NTA                            4663 non-null   object
 32  Latitude                       4788 non-null   float64
 33  Longitude                      4788 non-null   float64
dtypes: float64(6), int64(4), object(24)
memory usage: 1.3+ MB

In [67]:
GROCConfInspections.value_counts('Business Unique ID', ascending = False)

Business Unique ID
BA-1690979-2024    2
BA-1001621-2022    1
BA-1666365-2023    1
BA-1596353-2023    1
BA-1596402-2023    1
BA-1597771-2023    1
BA-1616765-2023    1
BA-1628903-2023    1
BA-1631875-2023    1
BA-1642873-2023    1
BA-1677877-2023    1
BA-1002976-2022    1
BA-1679440-2023    1
BA-1690494-2024    1
BA-1707531-2024    1
BA-1708856-2024    1
BA-1716203-2024    1
BA-1720823-2025    1
BA-1721260-2025    1
BA-1582436-2023    1
BA-1572278-2023    1
BA-1534786-2022    1
BA-1227987-2022    1
BA-1107968-2022    1
BA-1121078-2022    1
BA-1168744-2022    1
BA-1202042-2022    1
BA-1208677-2022    1
BA-1209860-2022    1
BA-1219880-2022    1
BA-1282904-2022    1
BA-1520854-2022    1
BA-1321896-2022    1
BA-1329374-2022    1
BA-1335574-2022    1
BA-1412248-2022    1
BA-1429125-2022    1
BA-1451804-2022    1
BA-1484729-2022    1
BA-1722946-2025    1
Name: count, dtype: int64

In [ ]:
GROCConfInspections.sort_values('', ascending = False)

In [65]:
GROCConfInspections.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41 entries, 4079 to 8727
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Certificate of Inspection      41 non-null     object
 1   Inspection Number              41 non-null     object
 2   Date of Occurance              41 non-null     object
 3   Year (added)                   41 non-null     object
 4   Business Unique ID             41 non-null     object
 5   UniqueBusinessID_NoYear        41 non-null     object
 6   Business Name                  41 non-null     object
 7   DBA Trade Name                 9 non-null      object
 8   Business Category              41 non-null     object
 9   Inspection type                41 non-null     object
 10  Device Category                41 non-null     object
 11  Device Class                   37 non-null     object
 12  Device Type                    41 non-null     object
 13  Devices Inspected              41 non-null     int64
 14  Devices Approved               41 non-null     int64
 15  Devices Condemned/Confiscated  41 non-null     int64
 16  Confiscated                    41 non-null     object
 17  Address Type                   41 non-null     object
 18  Building Number                41 non-null     object
 19  Street Name                    41 non-null     object
 20  Street Name 2                  0 non-null      object
 21  Unit Type                      2 non-null      object
 22  Unit                           2 non-null      object
 23  City                           41 non-null     object
 24  State                          41 non-null     object
 25  Postcode                       41 non-null     int64
 26  Borough                        41 non-null     object
 27  Community Board                41 non-null     float64
 28  Council District               41 non-null     float64
 29  BIN                            41 non-null     float64
 30  BBL                            41 non-null     float64
 31  NTA                            39 non-null     object
 32  Latitude                       41 non-null     float64
 33  Longitude                      41 non-null     float64
dtypes: float64(6), int64(4), object(24)
memory usage: 11.2+ KB

In [64]:
GROCConfInspections.to_csv("GroceryStoreConfiscations.csv")

In [24]:
WHOLEInspections.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49 entries, 7 to 1663
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Certificate of Inspection      49 non-null     object
 1   Inspection Number              49 non-null     object
 2   Date of Occurance              49 non-null     object
 3   Year (added)                   49 non-null     object
 4   Business Unique ID             49 non-null     object
 5   UniqueBusinessID_NoYear        49 non-null     object
 6   Business Name                  49 non-null     object
 7   DBA Trade Name                 7 non-null      object
 8   Business Category              49 non-null     object
 9   Inspection type                49 non-null     object
 10  Device Category                49 non-null     object
 11  Device Class                   48 non-null     object
 12  Device Type                    49 non-null     object
 13  Devices Inspected              49 non-null     int64
 14  Devices Approved               49 non-null     int64
 15  Devices Condemned/Confiscated  49 non-null     int64
 16  Confiscated                    2 non-null      object
 17  Address Type                   49 non-null     object
 18  Building Number                26 non-null     object
 19  Street Name                    49 non-null     object
 20  Street Name 2                  24 non-null     object
 21  Unit Type                      0 non-null      object
 22  Unit                           0 non-null      object
 23  City                           49 non-null     object
 24  State                          49 non-null     object
 25  Postcode                       49 non-null     int64
 26  Borough                        49 non-null     object
 27  Community Board                48 non-null     float64
 28  Council District               48 non-null     float64
 29  BIN                            24 non-null     float64
 30  BBL                            24 non-null     float64
 31  NTA                            23 non-null     object
 32  Latitude                       48 non-null     float64
 33  Longitude                      48 non-null     float64
dtypes: float64(6), int64(4), object(24)
memory usage: 13.4+ KB

In [73]:
WHOLEInspections.to_csv("Wholesale Food Confiscations.csv")

In [72]:
WHOLEInspections.sort_values('Devices Condemned/Confiscated', ascending = False)

,Certificate of Inspection,Inspection Number,Date of Occurance,Year (added),Business Unique ID,UniqueBusinessID_NoYear,Business Name,DBA Trade Name,Business Category,Inspection type,...,State,Postcode,Borough,Community Board,Council District,BIN,BBL,NTA,Latitude,Longitude
829,A0192175,INS-000790344,10/04/2024,2024,BA-1710814-2024,BA-1710814,"MADURA, JOHN D FARMS",NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.736531,-73.990752
629,A0192275,INS-000815755,10/04/2024,2024,BA-1710841-2024,BA-1710841,"SAMASCOTT ORCHARDS, LLC",NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
7,A0200942,INS-000804414,11/26/2024,2024,BA-1714440-2024,BA-1714440,WING Y MEATS INC,NaN,Wholesale Food Market - 718,Scale,...,NY,11222,Brooklyn,301.0,33.0,3066690.0,3.026640e+09,BK76,40.726249,-73.935830
1373,A0192254,INS-000790502,10/04/2024,2024,BA-1710837-2024,BA-1710837,DEEP MOUNTAIN MAPLE LLC,NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
1191,A0192295,INS-000790579,10/04/2024,2024,BA-1710847-2024,BA-1710847,JUQUILITA C.T. FARM,NaN,Wholesale Food Market - 718,Scale,...,NY,10924,Outside NYC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1192,A0162243,INS-000725642,04/05/2024,2024,BA-1330213-2022,BA-1330213,ITO EN (NORTH AMERICA) INC.,NaN,Wholesale Food Market - 718,Scale,...,NY,11232,Brooklyn,307.0,38.0,3336900.0,3.006870e+09,NaN,40.657614,-74.006880
1200,A0191760,INS-000789494,10/02/2024,2024,BA-1710649-2024,BA-1710649,"HAWTHORNE VALLEY ASSOCIATION, INC.",NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
1251,A0217161,INS-000832082,03/20/2025,2025,BA-1722361-2025,BA-1722361,"Gitto & Sons Health Food, Inc.",Gitto Farmer's Market,Wholesale Food Market - 718,Scale,...,NY,11236,Brooklyn,318.0,42.0,3337450.0,3.079200e+09,BK50,40.642922,-73.917447
1265,A0217161,INS-000832082,03/20/2025,2025,BA-1722361-2025,BA-1722361,"Gitto & Sons Health Food, Inc.",Gitto Farmer's Market,Wholesale Food Market - 718,Scale,...,NY,11236,Brooklyn,318.0,42.0,3337450.0,3.079200e+09,BK50,40.642922,-73.917447
1312,A0165233,INS-000734701,04/24/2024,2024,BA-1687406-2024,BA-1687406,"GB GREEN GASTRONOME, LLC",NaN,Wholesale Food Market - 718,Scale,...,NY,11428,Queens,413.0,23.0,4229855.0,4.107250e+09,QN34,40.719092,-73.734099
1323,A0186269,INS-000777390,09/04/2024,2024,BA-1707311-2024,BA-1707311,FINE COCOA PRODUCTS CORP.,NaN,Wholesale Food Market - 718,Scale,...,NY,11232,Brooklyn,307.0,38.0,3336900.0,3.006870e+09,BK32,40.656695,-74.006815
1369,A0191528,INS-000788762,10/02/2024,2024,BA-1710508-2024,BA-1710508,DI PAOLA TURKEYS INC,NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
1397,A0216338,INS-000837260,03/14/2025,2025,BA-1192106-2022,BA-1192106,"CHEF'S CHOICE CASH & CARRY FOOD DISTRIBUTOR, INC.",NaN,Wholesale Food Market - 718,Scale,...,NY,11203,Brooklyn,317.0,45.0,3104354.0,3.047350e+09,BK96,40.647234,-73.929888
1089,A0200485,INS-000802369,11/22/2024,2024,BA-1318503-2022,BA-1318503,KINGSLAND FOODS,NaN,Wholesale Food Market - 718,Scale,...,NY,11378,Queens,405.0,30.0,4437461.0,4.026030e+09,QN31,40.719904,-73.920010
1398,A0216386,INS-000837301,03/14/2025,2025,BA-1192106-2022,BA-1192106,"CHEF'S CHOICE CASH & CARRY FOOD DISTRIBUTOR, INC.",NaN,Wholesale Food Market - 718,Scale,...,NY,11203,Brooklyn,317.0,45.0,3104354.0,3.047350e+09,BK96,40.647234,-73.929888
1448,A0216338,INS-000837260,03/14/2025,2025,BA-1192106-2022,BA-1192106,"CHEF'S CHOICE CASH & CARRY FOOD DISTRIBUTOR, INC.",NaN,Wholesale Food Market - 718,Scale,...,NY,11203,Brooklyn,317.0,45.0,3104354.0,3.047350e+09,BK96,40.647234,-73.929888
1467,A0192123,INS-000789737,10/04/2024,2024,BA-1710703-2024,BA-1710703,CENTRAL VALLEY FARM,NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
1522,A0191749,INS-000789477,10/02/2024,2024,BA-1710646-2024,BA-1710646,"CARADONNA FARMS OF THE HUDSON VALLEY, INC.",NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
1569,A0192152,INS-000790303,10/04/2024,2024,BA-1710808-2024,BA-1710808,CAMPO ROSSO FARM,NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.736531,-73.990752
1573,A0191776,INS-000789528,10/02/2024,2024,BA-1710652-2024,BA-1710652,BREEZY HILL ORCHARD LLC,Breezy Hill Orchard and Cider Mill,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
1587,A0191654,INS-000789298,10/02/2024,2024,BA-1710617-2024,BA-1710617,BERRIED TREASURES FARMS LLC,Amoon Farms,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
1593,A0192316,INS-000790613,10/04/2024,2024,BA-1710854-2024,BA-1710854,BACK HOME FARM LLC,NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.736531,-73.990752
1607,A0162549,INS-000726923,04/09/2024,2024,BA-1689405-2024,BA-1689405,Aztec Imperio Inc.,NaN,Wholesale Food Market - 718,Scale,...,NY,10459,Bronx,202.0,17.0,2005389.0,2.026990e+09,BX33,40.822377,-73.896886
1636,A0201511,INS-000808961,12/01/2024,2024,BA-1710807-2024,BA-1710807,AMERICAN PRIDE SEAFOOD INC,NaN,Wholesale Food Market - 718,Scale,...,NY,10024,Manhattan,107.0,6.0,NaN,NaN,NaN,40.780651,-73.976418
1090,A0192160,INS-000790316,10/04/2024,2024,BA-1710810-2024,BA-1710810,JUST MADE BAKERY,Treelicious Orchard & Bakery,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.736531,-73.990752
888,A0205640,INS-000815933,12/31/2024,2024,BA-1717543-2024,BA-1717543,La Mina Meat & Provisions NY Corp.,NaN,Wholesale Food Market - 718,Scale,...,NY,11221,Brooklyn,304.0,37.0,3073810.0,3.032450e+09,BK78,40.698289,-73.923989
1005,A0211340,INS-000827702,02/11/2025,2025,BA-1717543-2024,BA-1717543,La Mina Meat & Provisions NY Corp.,NaN,Wholesale Food Market - 718,Scale,...,NY,11221,Brooklyn,304.0,37.0,3073810.0,3.032450e+09,BK78,40.698289,-73.923989
441,A0191695,INS-000789371,10/02/2024,2024,BA-1710628-2024,BA-1710628,TERHUNE ORCHARDS FARM & BAKERY,Terhune Orchards,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
77,A0191624,INS-000789240,10/02/2024,2024,BA-1710607-2024,BA-1710607,WILLOW WISP ORGANIC FARM,NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
91,A0185672,INS-000778385,08/29/2024,2024,BA-1707588-2024,BA-1707588,"WFM PRIVATE LABEL MANAGEMENT, INC.",NaN,Wholesale Food Market - 718,Scale,...,NY,11101,Queens,402.0,26.0,4005259.0,4.004540e+09,QN31,40.751142,-73.949752
116,A0196906,INS-000793824,10/31/2024,2024,BA-1711597-2024,BA-1711597,W.E.A.M. CORPORATION,NaN,Wholesale Food Market - 718,Scale,...,NY,10465,Bronx,210.0,13.0,2080400.0,2.055620e+09,BX52,40.824635,-73.820366
118,A0149537,INS-000699233,01/09/2024,2024,BA-1477512-2022,BA-1477512,victor provision inc.,NaN,Wholesale Food Market - 718,Scale,...,NY,11206,Brooklyn,301.0,34.0,3070908.0,3.030390e+09,BK78,40.710334,-73.934940
142,A0216745,INS-000830933,03/18/2025,2025,BA-1529433-2022,BA-1529433,victor provision inc.,NaN,Wholesale Food Market - 718,Scale,...,NY,11206,Brooklyn,301.0,34.0,3070908.0,3.030390e+09,BK78,40.710334,-73.934940
154,A0191672,INS-000789328,10/02/2024,2024,BA-1710621-2024,BA-1710621,"VAN HOUTEN, JAMES B",VanHouten Farms,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
220,A0178583,INS-000746538,07/17/2024,2024,BA-1696569-2024,BA-1696569,Twin Marquis Inc.,NaN,Wholesale Food Market - 718,Scale,...,NY,11206,Brooklyn,301.0,34.0,3325825.0,3.030560e+09,BK78,40.708275,-73.938748
251,A0178583,INS-000746538,07/17/2024,2024,BA-1696569-2024,BA-1696569,Twin Marquis Inc.,NaN,Wholesale Food Market - 718,Scale,...,NY,11206,Brooklyn,301.0,34.0,3325825.0,3.030560e+09,BK78,40.708275,-73.938748
278,A0192223,INS-000790444,10/04/2024,2024,BA-1710826-2024,BA-1710826,TOIGO ORCHARDS II,NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
444,A0186294,INS-000776725,09/04/2024,2024,BA-1549367-2022,BA-1549367,"TABLE 87, FROZEN, LLC",NaN,Wholesale Food Market - 718,Scale,...,NY,11232,Brooklyn,307.0,38.0,3010649.0,3.007160e+09,BK32,40.654059,-74.013050
14,A0200942,INS-000804414,11/26/2024,2024,BA-1714440-2024,BA-1714440,WING Y MEATS INC,NaN,Wholesale Food Market - 718,Scale,...,NY,11222,Brooklyn,301.0,33.0,3066690.0,3.026640e+09,BK76,40.726249,-73.935830
540,A0191803,INS-000789579,10/02/2024,2024,BA-1710657-2024,BA-1710657,"SYCAMORE FARMS, LLC",NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
541,A0192133,INS-000790267,10/04/2024,2024,BA-1710803-2024,BA-1710803,SUN SPROUT FARM LLC,NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.735889,-73.991210
559,A0195915,INS-000797127,10/25/2024,2024,BA-1538613-2022,BA-1538613,SUN MING JAN INC.,NaN,Wholesale Food Market - 718,Scale,...,NY,11206,Brooklyn,304.0,34.0,3071858.0,3.031480e+09,BK78,40.702888,-73.931186
612,A0191793,INS-000789561,10/02/2024,2024,BA-1710656-2024,BA-1710656,STONY MOUNTAIN RANCH,NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
688,A0192275,INS-000815755,10/04/2024,2024,BA-1710841-2024,BA-1710841,"SAMASCOTT ORCHARDS, LLC",NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
701,A0191815,INS-000789605,10/02/2024,2024,BA-1710666-2024,BA-1710666,"ROOTED FAMILY FARM, LLC",NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329
702,A0192126,INS-000789763,10/04/2024,2024,BA-1710712-2024,BA-1710712,RAMBLE CREEK FARM LLC,NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.735889,-73.991210
809,A0194989,INS-000792557,10/22/2024,2024,BA-1711307-2024,BA-1711307,MIDLAND MEAT PACKING NY INC.,NaN,Wholesale Food Market - 718,Scale,...,NY,11220,Brooklyn,307.0,38.0,3255737.0,3.008190e+09,BK32,40.646984,-74.022721
838,A0205640,INS-000815933,12/31/2024,2024,BA-1717543-2024,BA-1717543,La Mina Meat & Provisions NY Corp.,NaN,Wholesale Food Market - 718,Scale,...,NY,11221,Brooklyn,304.0,37.0,3073810.0,3.032450e+09,BK78,40.698289,-73.923989
1663,A0192139,INS-000790275,10/04/2024,2024,BA-1710807-2024,BA-1710807,AMERICAN PRIDE SEAFOOD INC,NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.736531,-73.990752

In [69]:
WHOLEConfInspections = WHOLEInspections.query("`Devices Condemned/Confiscated` > 0")

In [70]:
WHOLEConfInspections.sort_values('Devices Condemned/Confiscated', ascending = False)

,Certificate of Inspection,Inspection Number,Date of Occurance,Year (added),Business Unique ID,UniqueBusinessID_NoYear,Business Name,DBA Trade Name,Business Category,Inspection type,...,State,Postcode,Borough,Community Board,Council District,BIN,BBL,NTA,Latitude,Longitude
829,A0192175,INS-000790344,10/04/2024,2024,BA-1710814-2024,BA-1710814,"MADURA, JOHN D FARMS",NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.736531,-73.990752
629,A0192275,INS-000815755,10/04/2024,2024,BA-1710841-2024,BA-1710841,"SAMASCOTT ORCHARDS, LLC",NaN,Wholesale Food Market - 718,Scale,...,NY,10003,Manhattan,105.0,2.0,NaN,NaN,NaN,40.737133,-73.990329